ARCH=arm
CROSS_COMPILE=/media/Data/KERNEL/tools-master/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-
INSTALL_MOD_PATH=/media/Data/KERNEL/ModulZkouska/

obj-m = servoPi_modul.o

#SOURCE = /lib/modules/$(uname -r)/build

#PWD = $(pwd)

#default:
#	$(MAKE) -C $(SOURCE) M=$(PWD) modules
	
clear:
	rm -rf Module.symvers servoPi_modul.o servoPi_modul.ko servoPi_modul.mod.c modules.order servoPi_modul.mod.o .servoPi_modul.ko.cmd .tmp_versions .servoPi_modul.o.cmd .servoPi_modul.mod.o.cmd

